app = 'wordsearch-app'
primary_region = 'ord'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[[mounts]]
  source = "data"
  destination = "/data"
  initial_size = "1gb"